### ISSUE TITLE
Add info about creating a desktop entry for Wave in Linux installtion docs

### ISSUE THREAD

**Issue by YJDoc2** [wavetermdev/waveterm-docs#4]
Hey, just found this project and looks pretty interesting!

I installed it on Linux, and the quickstart docs show  that to run it cd into the extracted directory and run `./Wave` which will launch the terminal.

While this works, it is a bit tedious, and (for me) feels a bit rough around the edges to use.

So while looking for an alternatives, I found out about `.Desktop` files, and managed to create one for Wave. So now, I can launch it via my normal programs browser (on Pop-OS) like

![image](https://github.com/wavetermdev/waveterm-docs/assets/54112038/2f6ff6b1-b09c-45cb-ac25-90d865cd5dfb)

As well as pin it to dock to launch it via that :
![image](https://github.com/wavetermdev/waveterm-docs/assets/54112038/b9caf301-2e40-4b7f-b530-7b93be75b42e)

I can add the info on how to do it in docs if this project is fine with adding that ; but would need a bit of help for one of the  parts in that.

Let me know if this would be useful / you'd be willing to accept the PR.

Thanks :)

**Comment by tracymiranda** [comment]
Yes this would be great to add until we get round to better Linux support. If the instructions are relatively short (a paragraph) we can add it to the faq. Otherwise if longer we can do a separate page with a link from the faq. Let me know if any questions here or in discord.

**Comment by YJDoc2** [comment]
Hey @tracymiranda thanks! I have opened https://github.com/wavetermdev/waveterm-docs/pull/7 , please take a look.
