### ISSUE TITLE
Rename "Markdown editor" to "Code editor"

### ISSUE THREAD

**Issue by aklipfel** [wavetermdev/waveterm-docs#9]
Hey, 

Just discovered waveterm and reading the docs I was a bit confused as I expected to find a code editor in the terminal but only found doc about markdown and image viewer. I then read the "Markdown editor" to find out this was actually using code editor.

Shouldn't this section of the doc be called "Code Editor" for clarity ? I personnaly find it more appealing this way. 

If this is something to improve, I'd be happy to open a PR :)

**Comment by gonzolively** [comment]
Sorry this has been out so long, but the docs have been long updated and this issue is now resolved.
